/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AdvisorApplication = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'insuranceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllAdvisorApplications' : IDL.Func(
      [],
      [IDL.Vec(AdvisorApplication)],
      ['query'],
    ),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'submitAdvisorApplication' : IDL.Func([AdvisorApplication], [], []),
  'submitContactForm' : IDL.Func([ContactForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AdvisorApplication = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'insuranceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllAdvisorApplications' : IDL.Func(
        [],
        [IDL.Vec(AdvisorApplication)],
        ['query'],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'submitAdvisorApplication' : IDL.Func([AdvisorApplication], [], []),
    'submitContactForm' : IDL.Func([ContactForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };